id: P497E47F1
initial_creation_type: ocr
source_metadata:
  volumes:
    ce96c39c293744398c4d0bf1166e94e7:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: འབྲེལ་པ་བརྟག་པའི་འགྲེལ་པ།
      total_pages: 1198
      volume_number: 97
